### ISSUE TITLE
'Număr de cazuri pe zile' bar plot

### ISSUE THREAD

**Issue by vlabar-ice** [code4romania/date-la-zi#352] opened 2020-07-17 07:36 UTC
In the main bar plot 'Număr de cazuri pe zile', would be good to display the data for a more extended period of time, like in the Johns Hopkins app for daily cases. Otherwise the interpretation can be misleading. I know you can look at past data by clicking on the button in the lower-left corner, but that still displays data for the past couple of weeks only...If I only look at this, I wouldn't be too worries about the recent outbreak in Romania...so you need to broaden the graph to look at the bigger picture.

**Comment by catileptic** [comment] 2020-08-02 09:50
The problem with displaying more than 14 days is that the bars end up shrinking so much that you can not longer "read" the graph at a glance.

**Comment by web-sys1** [comment] 2020-08-04 21:14
@catileptic @vlabar-ice 
The problem is beside on graph. Same here.
![Screenshot_20200805-001229_Chrome](https://user-images.githubusercontent.com/61905565/89345668-80b2a180-d6b0-11ea-8141-3394752b6a97.jpg)

**Comment by web-sys1** [comment] 2020-08-04 21:18
If it is supposed to be an issue, it is appropriate to seek the answer over the discussion.

**Comment by catileptic** [comment] 2020-09-21 08:02
closing this since we are not taking action to implement a change.

**Closed by catileptic** 2020-09-21 08:02 UTC
